services:
  - type: web
    name: ai-maintenance-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ai_tracker_app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: Asia/Riyadh
      # One of the following depending on your DB choice:
      # - key: DATABASE_URL
      #   value: sqlite:////var/data/ai_tracker.db
    # If using SQLite, keep the disk:
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
