services:
  - type: web
    name: ai-maintenance-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: Asia/Riyadh
      # Choose ONE DB option (see next block)
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
