services:
  - type: web
    name: ai-maintenance-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: Asia/Riyadh
      - key: PYTHON_VERSION
        value: 3.11.8             # force Python 3.11 on Render
      # If you use SQLite + disk:
      # - key: DATABASE_URL
      #   value: sqlite:////var/data/ai_tracker.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

